### ISSUE TITLE
Callback URL

### ISSUE THREAD

**Issue by navygit** [5agado/fitbit-analyzer#4]
When using Oauth 2.0 authorization, what Callback URL should we use?

When i use https://google.com/

I get a problem (error) with the state parameter while running this program as described in previous issue.

When I use  http://127.0.0.1:8080

I get the same error message while creating my OAuth 2.0 authorization.

An idea how to solve this problem ?

**Comment by navygit** [comment]
404 Not Found
Missing parameters: state

Traceback (most recent call last):
  File "/Users/nkumar/Downloads/anaconda/envs/myenv3/lib/python3.4/site-packages/CherryPy-18.0.1-py3.4.egg/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
TypeError: index() missing 1 required positional argument: 'state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nkumar/Downloads/anaconda/envs/myenv3/lib/python3.4/site-packages/CherryPy-18.0.1-py3.4.egg/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/Users/nkumar/Downloads/anaconda/envs/myenv3/lib/python3.4/site-packages/CherryPy-18.0.1-py3.4.egg/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/Users/nkumar/Downloads/anaconda/envs/myenv3/lib/python3.4/site-packages/CherryPy-18.0.1-py3.4.egg/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Users/nkumar/Downloads/anaconda/envs/myenv3/lib/python3.4/site-packages/CherryPy-18.0.1-py3.4.egg/cherrypy/_cpdispatch.py", line 60, in __call__
    raise sys.exc_info()[1]
  File "/Users/nkumar/Downloads/anaconda/envs/myenv3/lib/python3.4/site-packages/CherryPy-18.0.1-py3.4.egg/cherrypy/_cpdispatch.py", line 58, in __call__
    test_callable_spec(self.callable, self.args, self.kwargs)
  File "/Users/nkumar/Downloads/anaconda/envs/myenv3/lib/python3.4/site-packages/CherryPy-18.0.1-py3.4.egg/cherrypy/_cpdispatch.py", line 157, in test_callable_spec
    raise cherrypy.HTTPError(404, message=message)
cherrypy._cperror.HTTPError: (404, 'Missing parameters: state')

**Comment by navygit** [comment]
I solved this problem using "https://www.google.com/" as Callback URL and then I got another error 👍 

In src/util/scrapper.py , these lines are executed


    server = Oauth2.OAuth2Server(clientId, clientSecret)
    server.browser_authorize()

After this , it takes me to https://www.google.com/?code=8323c4cec7e516656bd040ed6bd78621c628a3f0&state=oRoGveNVuSuQD24XPVKdGVGFaYOJuh#_=_

After that its stuck and when I stop the server by pressing ctrl + c , it gives me an error : 

ACCESS_TOKEN = server.oauth.session.token['access_token']
KeyError: 'access_token'

So, the following lines are not getting executed and i am not getting my data.

    ACCESS_TOKEN = server.oauth.session.token['access_token']
    REFRESH_TOKEN = server.oauth.session.token['refresh_token']


I am using Implicit grant flow instead of authorization grant flow. 

I tried the other way as well. But, it throws the same error again

**Comment by 5agado** [comment]
@navygit Do you pass your client ID and client secret as specified in the README?

**Comment by navygit** [comment]
Yes , I passed them as stated in README.



    fitbit-scraper --id  xxxxxx  --secret  xxxxxxxxxxxxxxxxxxxxxxxxxx --start 2018-09-05  --out /Users/nkumar/Documents/fitbit_scraper/fitbit-analyzer/data/

**Comment by navygit** [comment]
I solved this issue. working on a new issue now
